spring.application.name=auth-service

server.port=8080

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://ec2-13-49-123-197.eu-north-1.compute.amazonaws.com:8081/login/oauth2/code/google

app.jwt.secret=QuantityMeasurementApplicationSecretKey12345678901234567890
app.jwt.expiration=86400000

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG