spring.application.name=quantitymeasurement

server.port=8080

spring.datasource.url=jdbc:h2:mem:quantitydb

spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.path=/api-docs
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
# JWT Secret
app.jwt.secret=QuantityMeasurementApplicationSecretKey12345678901234567890

# 24 Hours
app.jwt.expiration=86400000
app.security.public-paths=/api/auth/**,/swagger-ui/**,/v3/api-docs/**,/actuator/health

logging.level.org.springframework.security=DEBUG